/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9bd4e5e1-98bb-4ec6-81a6-f9739662be58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_39ZBYa7kD",
    "aws_user_pools_web_client_id": "4m0licll01jobuk431pgnq5te5",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://qpgxbxs3n5dhznmttnbsyp233y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3bvpqszi3nhehfcbdjfd5aozre",
    "aws_user_files_s3_bucket": "amplifyapp1ec9c569e007481f8ddcc4fa641c43a6141428-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
